name: Send Test Email

on:
  workflow_dispatch:  # 수동 실행할 수 있게 설정

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-api-python-client google-auth google-auth-oauthlib

      - name: Run script
        run: python main.py
